### ISSUE TITLE
css.replaceAll is not a function

### ISSUE THREAD

**Issue by dispbd** [david-plugge/tailwindcss-extend#5]
Hello. Thanks for the wonderful plugin. It makes life a lot easier :)

Unfortunately, due to the framework we use, we have to use Nodejs v14, which does not support the `replaceAll()` function (it appears in v15). What causes the error:
![Code_kWGRpHs1IS](https://github.com/david-plugge/tailwindcss-extend/assets/45291423/b2df7c22-3f92-4591-b27e-4dfb2dabbfad)

This line can be replaced with regex, which works similarly:
![Code_RahzR6QoqD](https://github.com/david-plugge/tailwindcss-extend/assets/45291423/a8866872-f45e-4830-8230-d868c4dacdfa)

Can you release a patch with a fix?
We in the team would really like to use your plugin in our work as soon as possible. Thank you!

**Comment by david-plugge** [comment]
Hello, glad you like it.

Sure, that´s a quick one. I´ll try to change it later when i´m at home.
